[project]
name = "srex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncssh>=2.23.0",
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "typer>=0.26.3",
]

[dependency-groups]
dev = [
    "pyrefly>=0.60.0",
    "mypy>=2.1.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.15",
]
